import Head from 'next/head'
import Link from 'next/link'
import { sanityClient, urlFor } from '../lib/sanity'


const recipeQuery = `*[_type=="recipe"]{
  _id,
  name,
  slug,
  mainImage{
    asset->{
      _id,
      url
    }
  }
}`;



export default function Home({recipes}) {
  return (
    <div>
      <Head>
        <title>johns Kitchen 🍍</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to johns Kitchen 🍦</h1>

      <ul className='recipe-list'>
        {recipes?.length > 0 && recipes.map((recipe) => (
          <li key={recipe._id} className="recipe-card">
            <Link href={`/recipes/${recipe.slug.current}`}>
              <img src={urlFor(recipe.mainImage).url()} alt="" /> 
              <span>{recipe.name}</span>
            </Link>
          </li>
        ))}
      </ul>

    </div>
  )
}

export async function getStaticProps(){
  const recipes = await sanityClient.fetch(recipeQuery);
  return {props: {recipes}};
}